import { z } from "zod";

/**
 * Registering a camera. A camera is a name and an optional grouping label; the
 * ingest key and token are generated by the server on create, never supplied.
 * No RTSP URL or credentials — those live in the Edge Agent, not here.
 */
export const CreateCameraSchema = z.object({
  name: z.string().trim().min(1, "A camera needs a name").max(120),
  group: z.string().trim().max(120).optional(),
});
export type CreateCameraDto = z.infer<typeof CreateCameraSchema>;
